[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = chain+
lib_deps =
    lovyan03/LovyanGFX @ ^1.1.16
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.0
    adafruit/Adafruit SHT31 Library @ ^2.2.2
    adafruit/Adafruit BusIO @ ^1.15.0
    tzapu/WiFiManager @ ^2.0.17